version: "3.8"

services:
  backend:
    build: ./backend
    container_name: kmeans-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: kmeans-frontend
    ports:
      - "5173:80"
    restart: always
